# Generated by Django 3.2.18 on 2024-05-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_glossurl_sign_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ['gloss', 'language', 'ordering'], 'verbose_name': 'Translation equivalent', 'verbose_name_plural': 'Translation equivalents'},
        ),
        migrations.RemoveField(
            model_name='translation',
            name='order',
        ),
        migrations.AddField(
            model_name='translation',
            name='ordering',
            field=models.IntegerField(default=1, verbose_name='ordering'),
            preserve_default=False,
        ),
    ]
