# Generated by Django 3.2.18 on 2024-05-21 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0007_auto_20240521_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ortnamn_tecken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('ortnamn', models.CharField(blank=True, max_length=60, null=True, verbose_name='Ortnamn på svenska')),
                ('forklaring_svenska', models.TextField(blank=True, null=True, verbose_name='Förklaring svenskt namn')),
                ('forklaring_tecken', models.TextField(blank=True, null=True, verbose_name='Förklaring tecken STS')),
                ('teckenfilnamn', models.CharField(blank=True, max_length=60, null=True, verbose_name='Filnamn tecken med sökväg')),
                ('teckenfilnamn2', models.CharField(blank=True, max_length=60, null=True, verbose_name='Filnamn tecken 2 med sökväg')),
                ('teckenfilnamn3', models.CharField(blank=True, max_length=60, null=True, verbose_name='Filnamn tecken 3 med sökväg')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='Skapad datum')),
                ('changedate', models.DateTimeField(auto_now=True, verbose_name='Ändrad datum')),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Skapad av')),
                ('editedby', models.ForeignKey(blank=True, db_column='editedby', editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Uppdaterad av+', to=settings.AUTH_USER_MODEL, verbose_name='Uppdaterad av')),
            ],
            options={
                'verbose_name': 'Ortnamn',
                'verbose_name_plural': 'Ortnamn',
                'db_table': 'ortnamn_tecken',
            },
        ),
    ]
